title = "Daniel Pagotto"
author = "Daniel Pagotto"
#copyright = "2020-2021"
description = "Análise de dados, empreendedorismo, inovação e gestão"
profilePicture = "images/foto-daniel.jpg"
keywords = ""
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = []
mainSections = ["post"]
images = ["images/foto-daniel.jpg"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"


[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/daniel-do-prado-pagotto-bab62a50/"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/danielppagotto/"

[[socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/danielppagotto/"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:danielppagotto@gmail.com"
