baseURL = "https://danielppagotto.github.io/blog_Daniel/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Daniel Pagotto"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
publishDir = "docs/"

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
